/** Field + endpoint configs for generic CMS entity pages */

export const SECTION_TYPES = [
  { value: 'HERO', label: 'Hero Banner' },
  { value: 'SEARCH', label: 'Search / Filters' },
  { value: 'FEATURED_PROPERTIES', label: 'Featured Properties' },
  { value: 'PROPERTY_LIST', label: 'Property Listing' },
  { value: 'SERVICES', label: 'Services / Why Choose Us' },
  { value: 'TESTIMONIALS', label: 'Testimonials' },
  { value: 'STATS', label: 'Stats' },
  { value: 'PARTNERS', label: 'Partners' },
  { value: 'TEAM', label: 'Team' },
  { value: 'BLOG', label: 'Blog' },
  { value: 'FAQ', label: 'FAQ' },
  { value: 'CTA', label: 'Call to Action' },
  { value: 'COMPANY_INTRO', label: 'Company Introduction' },
  { value: 'MISSION_VISION', label: 'Mission & Vision' },
  { value: 'CONTACT_INFO', label: 'Contact Information' },
  { value: 'CUSTOM', label: 'Custom Content' },
];

export const CMS_ENTITIES = {
  banners: {
    title: 'Hero Banners',
    subtitle: 'Homepage and campaign banner slides',
    endpoint: '/cms/admin/banners',
    labelKey: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
      { key: 'image', label: 'Image URL', type: 'image', required: true },
      { key: 'badge', label: 'Badge', type: 'text' },
      { key: 'buttonText', label: 'Button Text', type: 'text' },
      { key: 'buttonLink', label: 'Button Link', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  services: {
    title: 'Services',
    subtitle: 'Why Choose Us / service cards',
    endpoint: '/cms/admin/services',
    labelKey: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'icon', label: 'Icon name', type: 'text', placeholder: 'shield, dollar, headphones…' },
      { key: 'image', label: 'Image URL', type: 'image' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  testimonials: {
    title: 'Testimonials',
    subtitle: 'Customer reviews shown on the website',
    endpoint: '/cms/admin/testimonials',
    labelKey: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'avatar', label: 'Avatar URL', type: 'image' },
      { key: 'rating', label: 'Rating (1–5)', type: 'number' },
      { key: 'text', label: 'Testimonial', type: 'textarea', required: true },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  faqs: {
    title: 'FAQs',
    subtitle: 'Frequently asked questions',
    endpoint: '/cms/admin/faqs',
    labelKey: 'question',
    fields: [
      { key: 'question', label: 'Question', type: 'text', required: true },
      { key: 'answer', label: 'Answer', type: 'textarea', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  team: {
    title: 'Team Members',
    subtitle: 'About page team section',
    endpoint: '/cms/admin/team',
    labelKey: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'designation', label: 'Designation', type: 'text', required: true },
      { key: 'bio', label: 'Bio', type: 'textarea' },
      { key: 'avatar', label: 'Avatar URL', type: 'image' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'linkedin', label: 'LinkedIn', type: 'text' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  partners: {
    title: 'Partners',
    subtitle: 'Partner logos and links',
    endpoint: '/cms/admin/partners',
    labelKey: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'logo', label: 'Logo URL', type: 'image' },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'order', label: 'Order', type: 'number' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  blogs: {
    title: 'Blog Posts',
    subtitle: 'Articles and market insights',
    endpoint: '/cms/admin/blogs',
    labelKey: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text', required: true },
      { key: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { key: 'content', label: 'Content', type: 'textarea', required: true },
      { key: 'coverImage', label: 'Cover Image', type: 'image' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'metaTitle', label: 'SEO Title', type: 'text' },
      { key: 'metaDescription', label: 'SEO Description', type: 'textarea' },
      { key: 'featured', label: 'Featured', type: 'boolean' },
      { key: 'isPublished', label: 'Published', type: 'boolean' },
    ],
  },
  agents: {
    title: 'Agents',
    subtitle: 'Linked agent profiles (User + Agent model)',
    endpoint: '/cms/admin/agents',
    labelKey: 'licenseNumber',
    fields: [
      { key: 'userId', label: 'User ID', type: 'number', required: true },
      { key: 'licenseNumber', label: 'License number', type: 'text' },
      { key: 'specializations', label: 'Specializations', type: 'textarea' },
      { key: 'experience', label: 'Experience (years)', type: 'number' },
      { key: 'about', label: 'About', type: 'textarea' },
      { key: 'rating', label: 'Rating', type: 'number' },
      { key: 'totalSales', label: 'Total sales', type: 'number' },
      { key: 'isVerified', label: 'Verified', type: 'boolean' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
};
